let strip = neopixel.create(DigitalPin.P0, 5, NeoPixelMode.RGB)
let Strip2 = neopixel.create(DigitalPin.P1, 5, NeoPixelMode.RGB)
basic.forever(function () {
    strip.clear()
    strip.range(0, input.lightLevel() + 10).showColor(neopixel.colors(NeoPixelColors.Yellow))
    strip.show()
    strip.clear()
    Strip2.range(0, input.acceleration(Dimension.X) / 250).showColor(neopixel.colors(NeoPixelColors.Red))
    Strip2.show()
})
